ITL-1 Implement Page header
bgellerth/To-do pull request #1
Opened 2023-05-26 09:57 UTC by bgellerth

2023-05-26 12:04 UTC, roli-wg requested changes

2023-05-26 12:04 UTC, roli-wg commented on src/components/Header.vue
> +  emit("todoAdded", "Add-one-todo");
Why do you need to emit "Add-one-todo" string can you just emit the todoAdded action without any parameters?

2023-05-26 12:04 UTC, roli-wg commented on src/components/Header.vue
> +.Add {
Please name the css classes with hyphenated (.example-class) format

2023-05-26 12:55 UTC, roli-wg requested changes

2023-05-26 12:55 UTC, roli-wg commented on src/components/TodoForm.vue
>  defineProps({
According to the style guid and best practices the defineProps and defineEmits declaration should be before the variable declaration so right after the imports

2023-05-30 11:49 UTC, roli-wg approved these changes

2023-05-30 12:42 UTC, merged

2023-05-30 12:58 UTC, komaromiGyorgy approved these changes