ITL-23 Make the input field to work, search the todo list for specific words
bgellerth/To-do pull request #4
Opened 2023-06-15 11:14 UTC by bgellerth

2023-06-16 13:44 UTC, kincsokiss requested changes

2023-06-16 13:44 UTC, kincsokiss commented on src/components/TodoForm.vue
> +const handleSearch = ref("");
Please use single quote instead of double. You can set this as config in you editor.

2023-06-19 10:49 UTC, kincsokiss approved these changes

2023-06-19 10:59 UTC, gerebdavid commented on src/components/TodoChecked.vue
> +  return () => {
Why you have to return the emit inside a function?

2023-06-20 05:55 UTC, merged