ITL-30 Change style to use tailwind CSS classes
bgellerth/To-do pull request #5
Opened 2023-06-22 09:11 UTC by bgellerth

2023-06-22 12:11 UTC, kincsokiss requested changes

2023-06-22 12:11 UTC, kincsokiss commented on src/assets/main.css
> +.dropdown-toggle{
Please format the content.

2023-06-22 12:11 UTC, kincsokiss commented on src/components/Header.vue
> +  (e: "todoAdded"): void;
Please check your editor settings and set to use single quote instead of double.

2023-06-23 06:53 UTC, kincsokiss requested changes

2023-06-23 06:53 UTC, kincsokiss commented on src/assets/main.css
> +    width: 125px;
Please format this part in the same way how the other classes are and remove the empty line.

2023-06-23 06:56 UTC, gerebdavid commented on src/components/PrioSelector.vue
> +        'h-3 w-3 rounded-full cursor-pointer md:!bg-white md:h-8 md:w-full md:rounded-full md:text-xs md:p-0',
Please create a class for this row, you are using it 3 times.

2023-06-23 06:57 UTC, gerebdavid commented on src/components/TodoForm.vue
> +        v-if="checkedTodos.length > 0"
checkedTodos.length is enough for the condition

2023-06-23 07:40 UTC, gerebdavid approved these changes

2023-06-26 11:08 UTC, merged